[tox]
envlist = lint,manifest,typing,py310,py311,py312,py313,coverage-report


[testenv]
setenv =
    PYTHONIOENCODING=UTF-8
# Disable loading kernel modules during unit tests
    W1THERMSENSOR_NO_KERNEL_MODULE=1
extras = {env:TOX_AP_TEST_EXTRAS:tests}
commands =
    coverage run -p -m pytest {posargs}


[testenv:integration]
commands = make docker-deb
allowlist_externals =
    make


[testenv:coverage-report]
basepython = python3.13
skip_install = true
deps = coverage[toml]>=7
commands =
    coverage combine
    coverage report
    coverage xml


[testenv:lint]
basepython = python3.13
skip_install = true
deps = ruff
commands =
    ruff format src/ tests/
    ruff check src/ tests/


[testenv:typing]
basepython = python3.13
deps =
    mypy
    types-aiofiles
commands =
    mypy src/ tests/


[testenv:manifest]
basepython = python3.13
deps = check-manifest
skip_install = true
commands = check-manifest


[testenv:news]
basepython = python3.13
deps = towncrier
commands = towncrier
