.TH "W1THERMSENSOR LS" "1" "05-Jun-2017" "" "w1thermsensor ls Manual"
.SH NAME
w1thermsensor\-ls \- List all available sensors
.SH SYNOPSIS
.B w1thermsensor ls
[OPTIONS]
.SH DESCRIPTION
List all available sensors
.SH OPTIONS
.TP
\fB\-t,\fP \-\-type [DS18S20|DS1822|DS18B20|MAX31850K|DS28EA00]
Show only sensor of this type
.TP
\fB\-j,\fP \-\-json
Output result in JSON format