.TH "W1THERMSENSOR PRECISION" "1" "05-Jun-2017" "" "w1thermsensor precision Manual"
.SH NAME
w1thermsensor\-precision \- Change the precision for the sensor and...
.SH SYNOPSIS
.B w1thermsensor precision
[OPTIONS] PRECISION id
.SH DESCRIPTION
Change the precision for the sensor and persist it in the sensor's EEPROM
.SH OPTIONS
.TP
\fB\-h,\fP \-\-hwid TEXT
The hardware id of the sensor
.TP
\fB\-t,\fP \-\-type [DS18S20|DS1822|DS18B20|MAX31850K|DS28EA00]
The type of the sensor